# config.yaml placeholder

paths:
  movies_path: "data/raw/tmdb_5000_movies.csv"
  credits_path: "data/raw/tmdb_5000_credits.csv"
  processed_data: "data/processed_movies.csv"
  transformed_data: "data/transformed_data.csv"
